"""Deletes user id column in comment

Revision ID: 399ff4d80c6d
Revises: 2a9b5af00639
Create Date: 2021-11-14 08:13:59.814030

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '399ff4d80c6d'
down_revision = '2a9b5af00639'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('comments_user_id_fkey', 'comments', type_='foreignkey')
    op.drop_column('comments', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('comments_user_id_fkey', 'comments', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
